### ISSUE TITLE
Dear Author，questions abount hdmap in carla dataset

### ISSUE THREAD

**Issue by BeautyCJ** [OpenDriveLab/ST-P3#10]
I download the carla data by this [url](https://github.com/autonomousvision/transfuser), but I did not find hdmap folder.

 I asked the author of Transfuser, he told me the topdown folder has the information about hdmap. Could U tell me your data processing? many thanks~~

**Comment by penghao-wu** [comment]
Hi, we upload a maps folder containing pre-processed map files and the script to generate the corresponding hdmap folder. Please have a look at it.
