### ISSUE TITLE
question about traffic lights in carla simulation

### ISSUE THREAD

**Issue by EcustBoy** [OpenDriveLab/ST-P3#18]
Hi author~  I would like to ask how to deal with traffic lights in stp3(e.g. stop in front of red light), I didn't see such behavior in your code,  I guess the traffic light information is already hidden in the waypoint information which is provided by route_planner? I'll thanks for your reply~

**Comment by ilnehc** [comment]
@EcustBoy Traffic light information is not explicitly provided in closed-loop test, as in most of algorithms working in CARLA.
