### ISSUE TITLE
Dear author, How to visualize the "occupancy" lshown like in the paper? 

### ISSUE THREAD

**Issue by emilyemliyM** [OpenDriveLab/ST-P3#4]
![image](https://user-images.githubusercontent.com/88700988/183826982-3bd84e3a-0bd7-4f9f-ad1c-52a3e602e713.png)
I can get the vehicle occupancy or pedestrian occupancy.

So how can I visualize them together shown in the picture?
Thanks a lot.

**Comment by charleshsc** [comment]
You can refer to the [https://github.com/OpenPerceptionX/ST-P3/blob/main/evaluate.py#L171](url) in the ST-P3/evaluate.py.
