### ISSUE TITLE
what kind of semantic segmentation model mentioned in the paper appendix? thx

### ISSUE THREAD

**Issue by emilyemliyM** [OpenDriveLab/ST-P3#7]

**Comment by ilnehc** [comment]
Sorry for the unclear part. It is MaskFormer with a Swin backbone.

**Comment by emilyemliyM** [comment]
> Sorry for the unclear part. It is MaskFormer with a Swin backbone.

Really thanks for the reply!

SO after the training in the Mapillary dataset, it just get the semantic output for the Nuscenes dataset in a test mode ?
Is that right?

Regards.

**Comment by ilnehc** [comment]
Correct.
