### ISSUE TITLE
Dear author, questions about carla data

### ISSUE THREAD

**Issue by BeautyCJ** [OpenDriveLab/ST-P3#9]
I got the carla dataset by directly downloading the dataset according to this url: https://github.com/autonomousvision/transfuser/tree/cvpr2021
but it did not contain hdmap in every folder,  how do you deal with this problem?~ thanks~

**Comment by ilnehc** [comment]
Duplicate of https://github.com/OpenPerceptionX/ST-P3/issues/10.
